// Ground vehicles research — category('armor') content:
//   - Per-vehicle progression graph (veh_wheel root -> vehicle nodes)
//   - Ground component tree (veh_comp_<tier>_<part>), columns x >= 2
// Runs in ServerEvents.recipes (fires on server start AND /reload).

var BLUE  = 0xFF2F6BD8
var EU_LV = 32
var EU_MV = 128
var EU_HV = 512
var EU_EV = 2048
var EU_IV = 8192

var pv = e => Item.of('wfcore:packaged_vehicle', '{entity:"' + e + '"}')

ServerEvents.recipes(event => {

    // =========================== VEHICLE GRAPH ROOT ============================

    WFResearch.builder('veh_wheel')
        .category('armor').pos(-4, 0)
        .nodeColor(BLUE)
        .name('Wheels & Running Gear')
        .description('Pneumatic tyres and running gear, the foundation every ground vehicle is built on.')
        .runs(20).ticksPerRun(300).eut(EU_LV).cwuPerRun(0)
        .itemPerRun(Item.of('gtceu:steel_plate', 4))
        .itemPerRun(Item.of('gtceu:rubber_plate', 8))
        .unlock(Item.of('superbwarfare:wheel'))
        .icon(Item.of('superbwarfare:wheel'))
        .register()

    // =========================== VEHICLE GRAPH — LV LOGISTICS ============================

    WFResearch.builder('veh_sodayo')
        .category('armor').pos(-4, 1)
        .nodeColor(BLUE)
        .name('Sodayo Pickup')
        .description('The Sodayo TenEven9 civilian pickup — the root of the ground-vehicle line.')
        .requires('veh_wheel')
        .runs(40).ticksPerRun(300).eut(EU_LV).cwuPerRun(0)
        .itemPerRun(Item.of('gtceu:steel_gearbox', 2))
        .itemPerRun(Item.of('gtceu:lv_electric_motor', 3))
        .itemPerRun(Item.of('superbwarfare:wheel', 4))
        .unlock(pv('superbwarfare:sodayo_pick_up'))
        .icon(pv('superbwarfare:sodayo_pick_up'))
        .register()

    WFResearch.builder('veh_truck')
        .category('armor').pos(-6, 2)
        .nodeColor(BLUE)
        .name('Cargo Truck')
        .description('A flatbed cargo truck for bulk resupply runs.')
        .requires('veh_sodayo')
        .runs(40).ticksPerRun(300).eut(EU_LV).cwuPerRun(0)
        .itemPerRun(Item.of('gtceu:steel_gearbox', 2))
        .itemPerRun(Item.of('gtceu:lv_electric_motor', 3))
        .itemPerRun(Item.of('superbwarfare:wheel', 4))
        .unlock(pv('superbwarfare:truck'))
        .icon(pv('superbwarfare:truck'))
        .register()

    WFResearch.builder('veh_ural')
        .category('armor').pos(-6, 3)
        .nodeColor(BLUE)
        .name('Ural Hauler')
        .description('A heavy 6x6 Ural military hauler for bulk logistics.')
        .requires('veh_truck')
        .runs(40).ticksPerRun(300).eut(EU_LV).cwuPerRun(0)
        .itemPerRun(Item.of('gtceu:steel_gearbox', 2))
        .itemPerRun(Item.of('gtceu:lv_electric_motor', 3))
        .itemPerRun(Item.of('superbwarfare:wheel', 4))
        .unlock(pv('mcsp:ural_green'))
        .icon(pv('mcsp:ural_green'))
        .register()

    // =========================== VEHICLE GRAPH — MV GUN TRUCKS ============================

    WFResearch.builder('veh_sodayo_hmg')
        .category('armor').pos(-4, 2)
        .nodeColor(BLUE)
        .name('Sodayo HMG')
        .description('Sodayo pickup with a pintle-mounted heavy machine gun — the earliest gun truck.')
        .requires('veh_sodayo')
        .runs(52).ticksPerRun(300).eut(EU_MV).cwuPerRun(19200)
        .itemPerRun(Item.of('gtceu:aluminium_plate', 6))
        .itemPerRun(Item.of('gtceu:mv_electric_motor', 2))
        .itemTagPerRun('gtceu:circuits/mv', 2)
        .unlock(pv('superbwarfare:sodayo_pick_up_hmg'))
        .icon(pv('superbwarfare:sodayo_pick_up_hmg'))
        .register()

    WFResearch.builder('veh_sodayo_mlrs')
        .category('armor').pos(-2, 2)
        .nodeColor(BLUE)
        .name('Sodayo MLRS')
        .description('Sodayo pickup with a multiple rocket launcher firing grapeshot rockets.')
        .requires('veh_sodayo')
        .runs(52).ticksPerRun(300).eut(EU_MV).cwuPerRun(19200)
        .itemPerRun(Item.of('gtceu:aluminium_plate', 6))
        .itemPerRun(Item.of('gtceu:mv_electric_motor', 2))
        .itemTagPerRun('gtceu:circuits/mv', 2)
        .unlock(pv('superbwarfare:sodayo_pick_up_rocket'))
        .icon(pv('superbwarfare:sodayo_pick_up_rocket'))
        .register()

    WFResearch.builder('veh_humvee_mg')
        .category('armor').pos(-4, 3)
        .nodeColor(BLUE)
        .name('Humvee (MG)')
        .description('Armoured Humvee with a remote-weapon-station machine gun.')
        .requires('veh_sodayo_hmg')
        .runs(52).ticksPerRun(300).eut(EU_MV).cwuPerRun(19200)
        .itemPerRun(Item.of('gtceu:aluminium_plate', 6))
        .itemPerRun(Item.of('gtceu:mv_electric_motor', 2))
        .itemTagPerRun('gtceu:circuits/mv', 2)
        .unlock(pv('mcsp:humvee_sand'))
        .icon(pv('mcsp:humvee_sand'))
        .register()

    WFResearch.builder('veh_humvee_mk19')
        .category('armor').pos(-2, 3)
        .nodeColor(BLUE)
        .name('Humvee Mk19')
        .description('Armoured Humvee with a Mk19 automatic grenade launcher.')
        .requires('veh_sodayo_mlrs')
        .runs(52).ticksPerRun(300).eut(EU_MV).cwuPerRun(19200)
        .itemPerRun(Item.of('gtceu:aluminium_plate', 6))
        .itemPerRun(Item.of('gtceu:mv_electric_motor', 2))
        .itemTagPerRun('gtceu:circuits/mv', 2)
        .unlock(pv('mcsp:humvee_mk19'))
        .icon(pv('mcsp:humvee_mk19'))
        .register()

    // =========================== VEHICLE GRAPH — HV IFVs ============================

    WFResearch.builder('veh_lav')
        .category('armor').pos(-3, 4)
        .nodeColor(BLUE)
        .name('LAV-150 Commando')
        .description('The first infantry fighting vehicle: a wheeled LAV-150 with a light cannon. Either Humvee leads here.')
        .anyOf('veh_humvee_mg', 'veh_humvee_mk19')
        .runs(80).ticksPerRun(300).eut(EU_HV).cwuPerRun(76800)
        .itemPerRun(Item.of('gtceu:stainless_steel_plate', 6))
        .itemPerRun(Item.of('gtceu:hv_electric_motor', 2))
        .itemTagPerRun('gtceu:circuits/hv', 2)
        .unlock(pv('y'))
        .icon(pv('y'))
        .register()

    WFResearch.builder('veh_bradley')
        .category('armor').pos(-3, 5)
        .nodeColor(BLUE)
        .name('M2 Bradley')
        .description('The M2 Bradley IFV with a TOW launcher and autocannon — the later, heavier IFV.')
        .requires('veh_lav')
        .runs(80).ticksPerRun(300).eut(EU_HV).cwuPerRun(76800)
        .itemPerRun(Item.of('gtceu:stainless_steel_plate', 6))
        .itemPerRun(Item.of('gtceu:hv_electric_motor', 2))
        .itemTagPerRun('gtceu:circuits/hv', 2)
        .unlock(pv('superbwarfare:bradley'))
        .icon(pv('superbwarfare:bradley'))
        .register()

    WFResearch.builder('veh_lav_ad')
        .category('armor').pos(-2, 6)
        .nodeColor(BLUE)
        .name('LAV-AD')
        .description('The LAV-AD air-defence vehicle: guided SAMs and an anti-air gun.')
        .requires('veh_bradley')
        .runs(80).ticksPerRun(300).eut(EU_HV).cwuPerRun(76800)
        .itemPerRun(Item.of('gtceu:stainless_steel_plate', 6))
        .itemPerRun(Item.of('gtceu:hv_electric_motor', 2))
        .itemTagPerRun('gtceu:circuits/hv', 2)
        .unlock(pv('superbwarfare:lav_ad'))
        .icon(pv('superbwarfare:lav_ad'))
        .register()

    // =========================== VEHICLE GRAPH — EV MBT / SPG ============================

    WFResearch.builder('veh_tank')
        .category('armor').pos(-4, 6)
        .nodeColor(BLUE)
        .name('ZTZ-99A MBT')
        .description('The ZTZ-99A main battle tank: heavy armour and a large-caliber main gun.')
        .requires('veh_bradley')
        .runs(88).ticksPerRun(300).eut(EU_EV).cwuPerRun(307200)
        .itemPerRun(Item.of('gtceu:titanium_plate', 6))
        .itemPerRun(Item.of('gtceu:ev_electric_motor', 2))
        .itemTagPerRun('gtceu:circuits/ev', 2)
        .unlock(pv('superbwarfare:ztz_99a'))
        .icon(pv('superbwarfare:ztz_99a'))
        .register()

    WFResearch.builder('veh_plz')
        .category('armor').pos(0, 6)
        .nodeColor(BLUE)
        .name('PLZ-05 SPG')
        .description('The PLZ-05 self-propelled howitzer: a tracked 155mm artillery piece — the third path off the Bradley.')
        .requires('veh_bradley')
        .runs(88).ticksPerRun(300).eut(EU_EV).cwuPerRun(307200)
        .itemPerRun(Item.of('gtceu:titanium_plate', 6))
        .itemPerRun(Item.of('gtceu:ev_electric_motor', 2))
        .itemTagPerRun('gtceu:circuits/ev', 2)
        .unlock(pv('superbwarfare:plz_05'))
        .icon(pv('superbwarfare:plz_05'))
        .register()

    // =========================== VEHICLE GRAPH — IV APEX ============================

    WFResearch.builder('veh_prism')
        .category('armor').pos(-4, 7)
        .nodeColor(BLUE)
        .name('Prism Tank')
        .description('The Prism Tank: an IV-tier energy MBT firing focused prismatic beams — the apex of the tank line, beyond the ZTZ-99A.')
        .requires('veh_tank')
        .runs(96).ticksPerRun(300).eut(EU_IV).cwuPerRun(1228800)
        .itemPerRun(Item.of('gtceu:tungsten_steel_plate', 6))
        .itemPerRun(Item.of('gtceu:iv_electric_motor', 2))
        .itemTagPerRun('gtceu:circuits/iv', 2)
        .unlock(pv('superbwarfare:prism_tank'))
        .icon(pv('superbwarfare:prism_tank'))
        .register()

    // =========================== GROUND COMPONENT TREE ============================
    // Five component families, four tiers. x = 2..6, y = 0..3.
    // MV+ anyOf: any ONE component of the previous tier unlocks this tier.
    // cwuPerRun @200t midpoints: MV 12800 / HV 51200 / EV 204800.

    // ---- LV tier — no compute, no anyOf ----
    WFResearch.builder('veh_comp_lv_vehicle_frame')
        .category('armor').pos(2, 0).nodeColor(BLUE)
        .name('LV Vehicle Frame').description('Assembler blueprint for the LV-tier Vehicle Frame used in ground-vehicle assembly.')
        .runs(5).ticksPerRun(200).eut(EU_LV).cwuPerRun(0)
        .itemPerRun(Item.of('gtceu:steel_plate', 4)).itemTagPerRun('gtceu:circuits/lv', 1)
        .unlock(Item.of('kubejs:lv_vehicle_frame')).icon(Item.of('kubejs:lv_vehicle_frame')).register()

    WFResearch.builder('veh_comp_lv_engine')
        .category('armor').pos(3, 0).nodeColor(BLUE)
        .name('LV Engine').description('Assembler blueprint for the LV-tier Engine used in ground-vehicle assembly.')
        .runs(5).ticksPerRun(200).eut(EU_LV).cwuPerRun(0)
        .itemPerRun(Item.of('gtceu:steel_plate', 4)).itemTagPerRun('gtceu:circuits/lv', 1)
        .unlock(Item.of('kubejs:lv_engine')).icon(Item.of('kubejs:lv_engine')).register()

    WFResearch.builder('veh_comp_lv_track')
        .category('armor').pos(4, 0).nodeColor(BLUE)
        .name('LV Track').description('Assembler blueprint for the LV-tier Track used in ground-vehicle assembly.')
        .runs(5).ticksPerRun(200).eut(EU_LV).cwuPerRun(0)
        .itemPerRun(Item.of('gtceu:steel_plate', 4)).itemTagPerRun('gtceu:circuits/lv', 1)
        .unlock(Item.of('kubejs:lv_track')).icon(Item.of('kubejs:lv_track')).register()

    WFResearch.builder('veh_comp_lv_cannon_barrel')
        .category('armor').pos(5, 0).nodeColor(BLUE)
        .name('LV Cannon Barrel').description('Assembler blueprint for the LV-tier Cannon Barrel used in ground-vehicle assembly.')
        .runs(5).ticksPerRun(200).eut(EU_LV).cwuPerRun(0)
        .itemPerRun(Item.of('gtceu:steel_plate', 4)).itemTagPerRun('gtceu:circuits/lv', 1)
        .unlock(Item.of('kubejs:lv_cannon_barrel')).icon(Item.of('kubejs:lv_cannon_barrel')).register()

    WFResearch.builder('veh_comp_lv_weapons_system')
        .category('armor').pos(6, 0).nodeColor(BLUE)
        .name('LV Weapons System').description('Assembler blueprint for the LV-tier Weapons System used in ground-vehicle assembly.')
        .runs(5).ticksPerRun(200).eut(EU_LV).cwuPerRun(0)
        .itemPerRun(Item.of('gtceu:steel_plate', 4)).itemTagPerRun('gtceu:circuits/lv', 1)
        .unlock(Item.of('kubejs:lv_weapons_system')).icon(Item.of('kubejs:lv_weapons_system')).register()

    // ---- MV tier — anyOf any LV component ----
    WFResearch.builder('veh_comp_mv_vehicle_frame')
        .category('armor').pos(2, 1).nodeColor(BLUE)
        .name('MV Vehicle Frame').description('Assembler blueprint for the MV-tier Vehicle Frame used in ground-vehicle assembly.')
        .anyOf('veh_comp_lv_vehicle_frame', 'veh_comp_lv_engine', 'veh_comp_lv_track', 'veh_comp_lv_cannon_barrel', 'veh_comp_lv_weapons_system')
        .runs(8).ticksPerRun(200).eut(EU_MV).cwuPerRun(12800)
        .itemPerRun(Item.of('gtceu:aluminium_plate', 4)).itemTagPerRun('gtceu:circuits/mv', 1)
        .unlock(Item.of('kubejs:mv_vehicle_frame')).icon(Item.of('kubejs:mv_vehicle_frame')).register()

    WFResearch.builder('veh_comp_mv_engine')
        .category('armor').pos(3, 1).nodeColor(BLUE)
        .name('MV Engine').description('Assembler blueprint for the MV-tier Engine used in ground-vehicle assembly.')
        .anyOf('veh_comp_lv_vehicle_frame', 'veh_comp_lv_engine', 'veh_comp_lv_track', 'veh_comp_lv_cannon_barrel', 'veh_comp_lv_weapons_system')
        .runs(8).ticksPerRun(200).eut(EU_MV).cwuPerRun(12800)
        .itemPerRun(Item.of('gtceu:aluminium_plate', 4)).itemTagPerRun('gtceu:circuits/mv', 1)
        .unlock(Item.of('kubejs:mv_engine')).icon(Item.of('kubejs:mv_engine')).register()

    WFResearch.builder('veh_comp_mv_track')
        .category('armor').pos(4, 1).nodeColor(BLUE)
        .name('MV Track').description('Assembler blueprint for the MV-tier Track used in ground-vehicle assembly.')
        .anyOf('veh_comp_lv_vehicle_frame', 'veh_comp_lv_engine', 'veh_comp_lv_track', 'veh_comp_lv_cannon_barrel', 'veh_comp_lv_weapons_system')
        .runs(8).ticksPerRun(200).eut(EU_MV).cwuPerRun(12800)
        .itemPerRun(Item.of('gtceu:aluminium_plate', 4)).itemTagPerRun('gtceu:circuits/mv', 1)
        .unlock(Item.of('kubejs:mv_track')).icon(Item.of('kubejs:mv_track')).register()

    WFResearch.builder('veh_comp_mv_cannon_barrel')
        .category('armor').pos(5, 1).nodeColor(BLUE)
        .name('MV Cannon Barrel').description('Assembler blueprint for the MV-tier Cannon Barrel used in ground-vehicle assembly.')
        .anyOf('veh_comp_lv_vehicle_frame', 'veh_comp_lv_engine', 'veh_comp_lv_track', 'veh_comp_lv_cannon_barrel', 'veh_comp_lv_weapons_system')
        .runs(8).ticksPerRun(200).eut(EU_MV).cwuPerRun(12800)
        .itemPerRun(Item.of('gtceu:aluminium_plate', 4)).itemTagPerRun('gtceu:circuits/mv', 1)
        .unlock(Item.of('kubejs:mv_cannon_barrel')).icon(Item.of('kubejs:mv_cannon_barrel')).register()

    WFResearch.builder('veh_comp_mv_weapons_system')
        .category('armor').pos(6, 1).nodeColor(BLUE)
        .name('MV Weapons System').description('Assembler blueprint for the MV-tier Weapons System used in ground-vehicle assembly.')
        .anyOf('veh_comp_lv_vehicle_frame', 'veh_comp_lv_engine', 'veh_comp_lv_track', 'veh_comp_lv_cannon_barrel', 'veh_comp_lv_weapons_system')
        .runs(8).ticksPerRun(200).eut(EU_MV).cwuPerRun(12800)
        .itemPerRun(Item.of('gtceu:aluminium_plate', 4)).itemTagPerRun('gtceu:circuits/mv', 1)
        .unlock(Item.of('kubejs:mv_weapons_system')).icon(Item.of('kubejs:mv_weapons_system')).register()

    // ---- HV tier — anyOf any MV component ----
    WFResearch.builder('veh_comp_hv_vehicle_frame')
        .category('armor').pos(2, 2).nodeColor(BLUE)
        .name('HV Vehicle Frame').description('Assembler blueprint for the HV-tier Vehicle Frame used in ground-vehicle assembly.')
        .anyOf('veh_comp_mv_vehicle_frame', 'veh_comp_mv_engine', 'veh_comp_mv_track', 'veh_comp_mv_cannon_barrel', 'veh_comp_mv_weapons_system')
        .runs(10).ticksPerRun(200).eut(EU_HV).cwuPerRun(51200)
        .itemPerRun(Item.of('gtceu:stainless_steel_plate', 4)).itemTagPerRun('gtceu:circuits/lv', 1)
        .unlock(Item.of('kubejs:hv_vehicle_frame')).icon(Item.of('kubejs:hv_vehicle_frame')).register()

    WFResearch.builder('veh_comp_hv_engine')
        .category('armor').pos(3, 2).nodeColor(BLUE)
        .name('HV Engine').description('Assembler blueprint for the HV-tier Engine used in ground-vehicle assembly.')
        .anyOf('veh_comp_mv_vehicle_frame', 'veh_comp_mv_engine', 'veh_comp_mv_track', 'veh_comp_mv_cannon_barrel', 'veh_comp_mv_weapons_system')
        .runs(10).ticksPerRun(200).eut(EU_HV).cwuPerRun(51200)
        .itemPerRun(Item.of('gtceu:stainless_steel_plate', 4)).itemTagPerRun('gtceu:circuits/lv', 1)
        .unlock(Item.of('kubejs:hv_engine')).icon(Item.of('kubejs:hv_engine')).register()

    WFResearch.builder('veh_comp_hv_track')
        .category('armor').pos(4, 2).nodeColor(BLUE)
        .name('HV Track').description('Assembler blueprint for the HV-tier Track used in ground-vehicle assembly.')
        .anyOf('veh_comp_mv_vehicle_frame', 'veh_comp_mv_engine', 'veh_comp_mv_track', 'veh_comp_mv_cannon_barrel', 'veh_comp_mv_weapons_system')
        .runs(10).ticksPerRun(200).eut(EU_HV).cwuPerRun(51200)
        .itemPerRun(Item.of('gtceu:stainless_steel_plate', 4)).itemTagPerRun('gtceu:circuits/lv', 1)
        .unlock(Item.of('kubejs:hv_track')).icon(Item.of('kubejs:hv_track')).register()

    WFResearch.builder('veh_comp_hv_cannon_barrel')
        .category('armor').pos(5, 2).nodeColor(BLUE)
        .name('HV Cannon Barrel').description('Assembler blueprint for the HV-tier Cannon Barrel used in ground-vehicle assembly.')
        .anyOf('veh_comp_mv_vehicle_frame', 'veh_comp_mv_engine', 'veh_comp_mv_track', 'veh_comp_mv_cannon_barrel', 'veh_comp_mv_weapons_system')
        .runs(10).ticksPerRun(200).eut(EU_HV).cwuPerRun(51200)
        .itemPerRun(Item.of('gtceu:stainless_steel_plate', 4)).itemTagPerRun('gtceu:circuits/lv', 1)
        .unlock(Item.of('kubejs:hv_cannon_barrel')).icon(Item.of('kubejs:hv_cannon_barrel')).register()

    WFResearch.builder('veh_comp_hv_weapons_system')
        .category('armor').pos(6, 2).nodeColor(BLUE)
        .name('HV Weapons System').description('Assembler blueprint for the HV-tier Weapons System used in ground-vehicle assembly.')
        .anyOf('veh_comp_mv_vehicle_frame', 'veh_comp_mv_engine', 'veh_comp_mv_track', 'veh_comp_mv_cannon_barrel', 'veh_comp_mv_weapons_system')
        .runs(10).ticksPerRun(200).eut(EU_HV).cwuPerRun(51200)
        .itemPerRun(Item.of('gtceu:stainless_steel_plate', 4)).itemTagPerRun('gtceu:circuits/lv', 1)
        .unlock(Item.of('kubejs:hv_weapons_system')).icon(Item.of('kubejs:hv_weapons_system')).register()

    // ---- EV tier — anyOf any HV component ----
    WFResearch.builder('veh_comp_ev_vehicle_frame')
        .category('armor').pos(2, 3).nodeColor(BLUE)
        .name('EV Vehicle Frame').description('Assembler blueprint for the EV-tier Vehicle Frame used in ground-vehicle assembly.')
        .anyOf('veh_comp_hv_vehicle_frame', 'veh_comp_hv_engine', 'veh_comp_hv_track', 'veh_comp_hv_cannon_barrel', 'veh_comp_hv_weapons_system')
        .runs(12).ticksPerRun(200).eut(EU_EV).cwuPerRun(204800)
        .itemPerRun(Item.of('gtceu:titanium_plate', 4)).itemTagPerRun('gtceu:circuits/mv', 1)
        .unlock(Item.of('kubejs:ev_vehicle_frame')).icon(Item.of('kubejs:ev_vehicle_frame')).register()

    WFResearch.builder('veh_comp_ev_engine')
        .category('armor').pos(3, 3).nodeColor(BLUE)
        .name('EV Engine').description('Assembler blueprint for the EV-tier Engine used in ground-vehicle assembly.')
        .anyOf('veh_comp_hv_vehicle_frame', 'veh_comp_hv_engine', 'veh_comp_hv_track', 'veh_comp_hv_cannon_barrel', 'veh_comp_hv_weapons_system')
        .runs(12).ticksPerRun(200).eut(EU_EV).cwuPerRun(204800)
        .itemPerRun(Item.of('gtceu:titanium_plate', 4)).itemTagPerRun('gtceu:circuits/mv', 1)
        .unlock(Item.of('kubejs:ev_engine')).icon(Item.of('kubejs:ev_engine')).register()

    WFResearch.builder('veh_comp_ev_track')
        .category('armor').pos(4, 3).nodeColor(BLUE)
        .name('EV Track').description('Assembler blueprint for the EV-tier Track used in ground-vehicle assembly.')
        .anyOf('veh_comp_hv_vehicle_frame', 'veh_comp_hv_engine', 'veh_comp_hv_track', 'veh_comp_hv_cannon_barrel', 'veh_comp_hv_weapons_system')
        .runs(12).ticksPerRun(200).eut(EU_EV).cwuPerRun(204800)
        .itemPerRun(Item.of('gtceu:titanium_plate', 4)).itemTagPerRun('gtceu:circuits/mv', 1)
        .unlock(Item.of('kubejs:ev_track')).icon(Item.of('kubejs:ev_track')).register()

    WFResearch.builder('veh_comp_ev_cannon_barrel')
        .category('armor').pos(5, 3).nodeColor(BLUE)
        .name('EV Cannon Barrel').description('Assembler blueprint for the EV-tier Cannon Barrel used in ground-vehicle assembly.')
        .anyOf('veh_comp_hv_vehicle_frame', 'veh_comp_hv_engine', 'veh_comp_hv_track', 'veh_comp_hv_cannon_barrel', 'veh_comp_hv_weapons_system')
        .runs(12).ticksPerRun(200).eut(EU_EV).cwuPerRun(204800)
        .itemPerRun(Item.of('gtceu:titanium_plate', 4)).itemTagPerRun('gtceu:circuits/mv', 1)
        .unlock(Item.of('kubejs:ev_cannon_barrel')).icon(Item.of('kubejs:ev_cannon_barrel')).register()

    WFResearch.builder('veh_comp_ev_weapons_system')
        .category('armor').pos(6, 3).nodeColor(BLUE)
        .name('EV Weapons System').description('Assembler blueprint for the EV-tier Weapons System used in ground-vehicle assembly.')
        .anyOf('veh_comp_hv_vehicle_frame', 'veh_comp_hv_engine', 'veh_comp_hv_track', 'veh_comp_hv_cannon_barrel', 'veh_comp_hv_weapons_system')
        .runs(12).ticksPerRun(200).eut(EU_EV).cwuPerRun(204800)
        .itemPerRun(Item.of('gtceu:titanium_plate', 4)).itemTagPerRun('gtceu:circuits/mv', 1)
        .unlock(Item.of('kubejs:ev_weapons_system')).icon(Item.of('kubejs:ev_weapons_system')).register()

    WFResearch.builder('veh_iv')
        .category('armor').pos(4, 4).nodeColor(BLUE)
        .name('IV Components')
        .description('Assembler blueprints for every IV-tier component: the IV vehicle frame, engine, track and weapons system, plus the IV aircraft wing and cockpit — the apex of the component lines.')
        .anyOf('veh_comp_ev_vehicle_frame', 'veh_comp_ev_engine', 'veh_comp_ev_track', 'veh_comp_ev_cannon_barrel', 'veh_comp_ev_weapons_system',
               'air_comp_ev_air_frame', 'air_comp_ev_wing', 'air_comp_ev_rotor', 'air_comp_ev_cockpit')
        .runs(16).ticksPerRun(200).eut(EU_IV).cwuPerRun(819200)
        .itemPerRun(Item.of('gtceu:tungsten_steel_plate', 4)).itemTagPerRun('gtceu:circuits/ev', 1)
        .unlocks(Item.of('kubejs:iv_vehicle_frame'), Item.of('kubejs:iv_engine'), Item.of('kubejs:iv_track'),
                 Item.of('kubejs:iv_weapons_system'), Item.of('kubejs:iv_wing'), Item.of('kubejs:iv_cockpit'))
        .icon(Item.of('kubejs:iv_vehicle_frame')).register()

})
